### ISSUE TITLE
No CocoonIO support (Canvas+)

### ISSUE THREAD

**Issue by AndreasReitberger** [cranberrygame/phonegap-plugin-ad-admob#14]
Hi @cranberrygame 

Do you plan to add support for canvas+ to this plugin?
At the moment it's not workign (sadly).

Regargds
Andy

**Comment by mukeshphulwani66** [comment]
COMPILER ERROR: 

/workspace/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/workspace/platforms/android/src/com/cranberrygame/cordova/plugin/ad/admob/AdMobOverlap.java:576: error: AdMobOverlap.MyRewardedVideoListener is not abstract and does not override abstract method onRewardedVideoCompleted() in RewardedVideoAdListener
	class MyRewardedVideoListener implements RewardedVideoAdListener {
	^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /workspace/platforms/android/src/com/ludei/CocoonApp.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileArmv7ReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

CORDOVA LOG: 



skipping existing file: AdMobOverlap.java
skipping existing file: AdMobPlugin.java
skipping existing file: AdMobSplit.java
skipping existing file: AdMobOverlap.h
skipping existing file: AdMobOverlap.m
skipping existing file: AdMobPlugin.h
skipping existing file: AdMobPlugin.m
skipping existing file: AdMobSplit.h
skipping existing file: AdMobSplit.m
skipping existing file: windows.zip
skipping existing file: AdMobOverlap.cs
skipping existing file: AdMobPlugin.cs
skipping existing file: AdMobSplit.cs
skipping existing file: Silverlight.Md5.dll
skipping existing file: tests.js
skipping existing file: admob.js
[36m[2018-05-29 13:35:45.480] [DEBUG] AndroidBuilder - [39m[build]
[36m[2018-05-29 13:35:45.481] [DEBUG] AndroidBuilder - [39m[build] create certs folder
[36m[2018-05-29 13:35:45.482] [DEBUG] AndroidBuilder - [39m[build] keystore
[36m[2018-05-29 13:35:45.704] [DEBUG] AndroidBuilder - [39m[build] create release build.json
[36m[2018-05-29 13:35:45.705] [DEBUG] AndroidBuilder - [39m[build] call cordova
cp: dest file already exists: /workspace/plugins/cordova-plugin-ad-admob/LICENSE

cp: dest file already exists: /workspace/plugins/cordova-plugin-ad-admob/LICENSE
cp: dest file already exists: /workspace/plugins/cordova-plugin-ad-admob/README.md

skipping existing file: ad_unit1.png
skipping existing file: ad_unit2.png
skipping existing file: ad_unit3.png
skipping existing file: ad_unit4.png
skipping existing file: ad_unit5.png
skipping existing file: ad_unit6.png
skipping existing file: ad_unit7.png
skipping existing file: ad_unit8.png
skipping existing file: admob_mediation1.png
skipping existing file: admob_mediation2.png
skipping existing file: admob_mediation3.png
skipping existing file: admob_mediation4.png
skipping existing file: admob_mediation5.png
skipping existing file: admob_mediation6.png
skipping existing file: admob_mediation7.png
skipping existing file: CordovaApp-debug.apk
skipping existing file: ios_submit_for_review_survey.png
skipping existing file: index.html
skipping existing file: index.html
skipping existing file: index.html
skipping existing file: index.html
cp: dest file already exists: /workspace/plugins/cordova-plugin-ad-admob/LICENSE
cp: dest file already exists: /workspace/plugins/cordova-plugin-ad-admob/README.md
cp: dest file already exists: /workspace/plugins/cordova-plugin-ad-admob/package.json

cp: dest file already exists: /workspace/plugins/cordova-plugin-ad-admob/LICENSE
cp: dest file already exists: /workspace/plugins/cordova-plugin-ad-admob/README.md
cp: dest file already exists: /workspace/plugins/cordova-plugin-ad-admob/package.json
cp: dest file already exists: /workspace/plugins/cordova-plugin-ad-admob/plugin.xml

skipping existing file: AdMobOverlap.java
skipping existing file: AdMobPlugin.java
skipping existing file: AdMobSplit.java
skipping existing file: AdMobOverlap.h
skipping existing file: AdMobOverlap.m
skipping existing file: AdMobPlugin.h
skipping existing file: AdMobPlugin.m
skipping existing file: AdMobSplit.h
skipping existing file: AdMobSplit.m
skipping existing file: windows.zip
skipping existing file: AdMobOverlap.cs
skipping existing file: AdMobPlugin.cs
skipping existing file: AdMobSplit.cs
skipping existing file: Silverlight.Md5.dll
skipping existing file: tests.js
skipping existing file: admob.js
ANDROID_HOME=/opt/cocoon_compiler/workspace/production/data/sdks/android-sdks-linux
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
Subproject Path: CordovaLib
Starting a Gradle Daemon, 26 stopped Daemons could not be reused, use --status for details
null
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
	at build_5ez0hydd3ik82xf523d3ojhzc.run(/workspace/platforms/android/build.gradle:140)
org.xwalk:xwalk_core_library:22+
Not writing assets/xwalk-command-line since file already exists.
The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.
Incremental java compilation is an incubating feature.
The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.
:preBuild UP-TO-DATE
:preArmv7ReleaseBuild UP-TO-DATE
:checkArmv7ReleaseManifest
:preArmv7DebugBuild UP-TO-DATE
:preX86DebugBuild UP-TO-DATE
:preX86ReleaseBuild UP-TO-DATE
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugShaders
:CordovaLib:compileDebugShaders
:CordovaLib:generateDebugAssets
:CordovaLib:mergeDebugAssets
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:processDebugManifest
:CordovaLib:generateDebugBuildConfig
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:incrementalDebugJavaCompilationSafeguard
:CordovaLib:compileDebugJavaWithJavac
:CordovaLib:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForDebug
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug
:CordovaLib:mergeDebugJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForDebug
:CordovaLib:transformNative_libsWithSyncJniLibsForDebug
:CordovaLib:bundleDebug
:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseShaders
:CordovaLib:compileReleaseShaders
:CordovaLib:generateReleaseAssets
:CordovaLib:mergeReleaseAssets
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:processReleaseManifest
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:incrementalReleaseJavaCompilationSafeguard
:CordovaLib:compileReleaseJavaWithJavac
:CordovaLib:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForRelease
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease
:CordovaLib:mergeReleaseJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForRelease
:CordovaLib:transformNative_libsWithSyncJniLibsForRelease
:CordovaLib:bundleRelease
:prepareComAndroidSupportCustomtabs2420Library
:preArmv7DebugAndroidTestBuild UP-TO-DATE
:preX86DebugAndroidTestBuild UP-TO-DATE
:prepareComAndroidSupportMultidex101Library
:prepareComAndroidSupportSupportCompat2420Library
:prepareComAndroidSupportSupportCoreUi2420Library
:prepareComAndroidSupportSupportCoreUtils2420Library
:prepareComAndroidSupportSupportFragment2420Library
:prepareComAndroidSupportSupportMediaCompat2420Library
:prepareComAndroidSupportSupportV42420Library
:prepareComGoogleAndroidGmsPlayServicesAds1501Library
:prepareComGoogleAndroidGmsPlayServicesAdsBase1501Library
:prepareComGoogleAndroidGmsPlayServicesAdsIdentifier1501Library
:prepareComGoogleAndroidGmsPlayServicesAdsLite1501Library
:prepareComGoogleAndroidGmsPlayServicesAudience1501Library
:prepareComGoogleAndroidGmsPlayServicesBase1501Library
:prepareComGoogleAndroidGmsPlayServicesBasement1501Library
:prepareComGoogleAndroidGmsPlayServicesDrive1501Library
:prepareComGoogleAndroidGmsPlayServicesGames1501Library
:prepareComGoogleAndroidGmsPlayServicesGass1501Library
:prepareComGoogleAndroidGmsPlayServicesPlus1501Library
:prepareComGoogleAndroidGmsPlayServicesTasks1501Library
:prepareOrgApacheCordovaCordovaLib623ReleaseLibrary
:prepareOrgXwalkXwalk_core_library22525614Library
:prepareWebviewplusReleaseLibrary
:prepareArmv7ReleaseDependencies
:compileArmv7ReleaseAidl
:compileArmv7ReleaseRenderscript
:generateArmv7ReleaseBuildConfig
:generateArmv7ReleaseResValues
:generateArmv7ReleaseResources
:mergeArmv7ReleaseResources
:processArmv7ReleaseManifest
:processArmv7ReleaseResources
:generateArmv7ReleaseSources
:incrementalArmv7ReleaseJavaCompilationSafeguard
:compileArmv7ReleaseJavaWithJavac
:compileArmv7ReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/workspace/platforms/android/src/com/cranberrygame/cordova/plugin/ad/admob/AdMobOverlap.java:576: error: AdMobOverlap.MyRewardedVideoListener is not abstract and does not override abstract method onRewardedVideoCompleted() in RewardedVideoAdListener
	class MyRewardedVideoListener implements RewardedVideoAdListener {
	^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /workspace/platforms/android/src/com/ludei/CocoonApp.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
:compileArmv7ReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileArmv7ReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 32.704 secs

> please help i am getting this error while compiling it with cocoon
